server:
  port: 8080
spring:
  profiles:
    active: ci
  application:
    name: authentication-service
  sql:
    init:
      continue-on-error: true
      mode: never
  jpa:
    hibernate:
      ddl-auto: none
#Eureka
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
