name: Generate Swagger Docs and Push to Another Repo

on:
  push:
    branches:
      - main  # Ajuste para a branch que deseja monitorar
  pull_request:
    branches:
      - main

jobs:
  generate-and-push-docs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Build the application
        run: |
          ./mvnw clean install

      - name: Generate Swagger Documentation
        run: |
          ./mvnw springdoc-openapi:generate

      - name: Clone target repository
        run: |
          git clone https://github.com/Global-lanz/documentation.github.io documentation.github.io
          cd documentation.github.io
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"

      - name: Copy Swagger Documentation
        run: |
          cp target/openapi.json documentation.github.io/openapi.json
          cd documentation.github.io
          git add openapi.json
          git commit -m "Update Swagger documentation [$(date)]" || echo "No changes to commit"
          git push https://x-access-token:${{ secrets.TARGET_REPO_TOKEN }}@github.com/Global-lanz/documentation.github.io main
