name: Generate Swagger Docs and Push to Another Repo

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  generate-and-push-docs:
    permissions: write-all
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Build the application
        run: mvn -B package --file pom.xml  # Usa Maven diretamente

      - name: Generate Swagger Documentation
        run: mvn -B springdoc-openapi:generate --file pom.xml  # Usa Maven sem mvnw

      - name: Clone target repository
        run: |
          git clone https://github.com/Global-lanz/documentation.github.io documentation.github.io
          cd documentation.github.io
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"

      - name: Copy Swagger Documentation
        run: |
          cp target/openapi.json documentation.github.io/openapi.json
          cd documentation.github.io
          git add openapi.json
          git commit -m "Update Swagger documentation [$(date)]" || echo "No changes to commit"
          git push https://x-access-token:${{ secrets.TARGET_REPO_TOKEN }}@github.com/Global-lanz/documentation.github.io main
