name: Generate OpenAPI Spec

on:
  pull_request:
    types: [opened, synchronize, labeled, unlabeled]
    branches: [ "main" ]

jobs:
  generate-openapi:
    permissions: write-all
    runs-on: ubuntu-latest

    env:
      IMAGE_NAME: maiconlanzendorf/authentication-service

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Build application
        run: ./mvnw clean package -DskipTests

      - name: Run app in background (on port 8080)
        run: |
          java -Dspring.profiles.active=ci -Dserver.port=8080 -jar target/*.jar > app.log 2>&1 &
          sleep 120  # Aumentando o tempo de espera para garantir que a aplicação tenha tempo suficiente para iniciar

      - name: Show logs to verify if the app started
        run: tail -n 100 app.log

      - name: Check if server is listening on the expected port
        run: |
          netstat -an | grep 8080  # Verifique se a aplicação está ouvindo na porta 8080
          netstat -an | grep 8081  # Verifique se a aplicação está ouvindo na porta 8081

      - name: Fetch OpenAPI JSON
        run: curl -v http://localhost:8080/v3/api-docs -o openapi.json
        # Adicionando '-v' (verbose) para obter mais detalhes da falha caso haja erro

      - name: Upload openapi.json
        uses: actions/upload-artifact@v3.1.2
        with:
          name: openapi-spec
          path: openapi.json

      - name: Clone swagger repo
        run: git clone https://github.com/Global-lanz/documentation.github.io.git swagger-docs

      - name: Copy OpenAPI to docs repo
        run: |
          cp openapi.json swagger-docs/openapi/${{ env.IMAGE_NAME }}.json
          cd swagger-docs
          git config user.name "github-actions"
          git config user
